version: '2.26.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
  rabbitmq:
    image: 4.0.5-management-alpine
    container-name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    ports:
      - 5672:5673 
