version: '2.26.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASS}
      - POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"